/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvRouteImport } from './routes/cv'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ResidencyRouteImport } from './routes/residency'
import { Route as StatementRouteImport } from './routes/statement'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencyRoute = ResidencyRouteImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementRoute = StatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/portfolio': typeof PortfolioRoute
  '/residency': typeof ResidencyRoute
  '/statement': typeof StatementRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/portfolio': typeof PortfolioRoute
  '/residency': typeof ResidencyRoute
  '/statement': typeof StatementRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/portfolio': typeof PortfolioRoute
  '/residency': typeof ResidencyRoute
  '/statement': typeof StatementRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cv' | '/portfolio' | '/residency' | '/statement' | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv' | '/portfolio' | '/residency' | '/statement' | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/portfolio'
    | '/residency'
    | '/statement'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  PortfolioRoute: typeof PortfolioRoute
  ResidencyRoute: typeof ResidencyRoute
  StatementRoute: typeof StatementRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residency': {
      id: '/residency'
      path: '/residency'
      fullPath: '/residency'
      preLoaderRoute: typeof ResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement': {
      id: '/statement'
      path: '/statement'
      fullPath: '/statement'
      preLoaderRoute: typeof StatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  PortfolioRoute: PortfolioRoute,
  ResidencyRoute: ResidencyRoute,
  StatementRoute: StatementRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
